server {
  listen 80;
  server_name _;

  # Dossier racine de ton build Vite
  root /usr/share/nginx/html;
  index index.html;

  # Cache agressif pour les assets (vite génère des hash -> safe)
  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|json)$ {
    expires 30d;
    add_header Cache-Control "public, max-age=2592000";
    try_files $uri =404;
  }

  # SPA fallback : obligatoire pour React Router
  location / {
    try_files $uri /index.html;
  }

  # Sécurité minimale (tu peux renforcer après)
  add_header X-Content-Type-Options nosniff always;
  add_header X-Frame-Options SAMEORIGIN always;
  add_header X-XSS-Protection "1; mode=block" always;
}
