<?php

declare(strict_types=1);

namespace Pilotage\Application\Service;

/** Validated team snapshot, 2026-10-04; independent of development data and Markdown. */
final class TrackingSnapshot
{
    public const ROWS = [
        ['D01', 'done', 'Inscription et création de l’espace citoyen disponibles.', 'site', '/inscription'],
        ['D03', 'done', 'Connexion et accès à l’espace personnel disponibles.', 'site', '/connexion'],
        ['D04', 'done', 'Envoi d’un message à la mairie avec confirmation.', 'site', '/espace/demandes/nouvelle?type=contact'],
        ['D05', 'done', 'Catalogue et fiches des services municipaux disponibles.', 'site', '/services'],
        ['D06', 'done', 'Actualités de la ville consultables en ligne.', 'site', '/actualites'],
        ['D07', 'done', 'Accueil avec services prioritaires et dernières actualités.', 'site', '/'],
        ['D08', 'done', 'Gestion des membres et de leurs rôles disponible.', 'admin', '/admin/member'],
        ['D09', 'done', 'Accès aux outils administratifs contrôlé par permissions.', 'admin', '/admin/role'],
        ['D11', 'done', 'Suivi des demandes avec état et chronologie.', 'site', '/espace/demandes'],
        ['D12', 'done', 'Guide de démarrage en trois étapes dans l’espace citoyen.', 'site', '/espace'],
        ['D13', 'done', 'Libellés simplifiés et glossaire disponibles.', 'site', '/aide/glossaire'],
        ['D15', 'done', 'Fil d’Ariane disponible pour se repérer dans les pages.', 'site', '/services'],
        ['D16', 'done', 'Confirmation avec référence après l’envoi d’une demande.', 'site', '/espace/demandes/nouvelle?type=contact'],
        ['D17', 'done', 'Compteur des demandes en attente dans la file des agents.', 'admin', '/demandes'],
        ['D18', 'done', 'Publication d’alertes générales visibles en temps réel.', 'admin', '/contenus/alertes'],
        ['D19', 'done', 'Flux des demandes Webcup et suivi de l’équipe disponibles.', 'admin', '/pilotage'],
        ['D20', 'done', 'Réglages d’accessibilité intégrés aux parcours habituels.', 'site', '/'],
        ['F21', 'done', 'Repères, champs et annonces adaptés aux lecteurs d’écran.', 'site', '/inscription'],
        ['F22', 'done', 'File des demandes avec filtres et traitement par les agents.', 'admin', '/demandes'],
        ['F23', 'done', 'Mode contraste élevé disponible dans le panneau Affichage.', 'site', '/'],
        ['F24', 'done', 'Taille du texte réglable dans le panneau Affichage.', 'site', '/'],
        ['F25', 'done', 'Signalement d’un problème avec description et lieu.', 'site', '/espace/demandes/nouvelle?type=report'],
        ['F26', 'done', 'Historique des demandes disponible dans l’espace personnel.', 'site', '/espace/demandes'],
        ['F28', 'done', 'Services prioritaires mis en avant sur l’accueil.', 'site', '/'],
        ['F29', 'done', 'Publication d’alertes ciblées par quartier disponible.', 'admin', '/contenus/alertes'],
        ['F30', 'done', 'Annonces importantes signalées dans les notifications.', 'site', '/espace'],
        ['F31', 'done', 'Recommandations sanitaires diffusées aux citoyens consentants.', 'admin', '/contenus/alertes'],
        ['F32', 'done', 'Recherche de services par mot-clé et catégorie.', 'site', '/services'],
        ['F33', 'done', 'Suppression de son compte depuis le profil citoyen.', 'site', '/espace/profil'],
        ['F34', 'done', 'Consultation et suspension des comptes citoyens disponibles.', 'admin', '/admin/citizens'],
        ['F35', 'done', 'Astuces contextuelles disponibles pour les premières actions.', 'site', '/services'],
        ['F36', 'done', 'Horaires et informations des transports sur les fiches services.', 'site', '/services'],
        ['F37', 'done', 'Protection des connexions et journal des blocages disponibles.', 'admin', '/admin/security'],
        ['F38', 'done', 'État des services, retour prévu et alternatives affichés.', 'site', '/services'],
        ['F39', 'done', 'Réservation, déplacement et annulation de rendez-vous disponibles.', 'site', '/espace/rendez-vous'],
        ['F40', 'in_progress', 'Rappels de rendez-vous implémentés ; planification à vérifier.', 'site', '/espace/rendez-vous'],
        ['F41', 'done', 'Navigation au clavier et focus visible disponibles.', 'site', '/'],
        ['F42', 'done', 'Champs, aides et erreurs reliés pour les technologies d’assistance.', 'site', '/inscription'],
        ['F43', 'done', 'États distingués par un libellé et une icône.', 'site', '/espace/demandes'],
        ['F44', 'done', 'Mise en page adaptée au zoom et aux petits écrans.', 'site', '/'],
        ['F47', 'done', 'Journal des actions avec recherche et filtres disponible.', 'admin', '/admin/journal'],
        ['F48', 'done', 'Auteur, date et détail des modifications consultables.', 'admin', '/admin/journal'],
        ['F49', 'done', 'Notifications des changements d’état des demandes disponibles.', 'site', '/espace'],
        ['F50', 'done', 'Tableau de bord de l’activité disponible pour les agents.', 'admin', '/pilotage/tableau-de-bord'],
        ['F51', 'done', 'Information sur les données et dépôt d’inquiétudes disponibles.', 'site', '/espace/participation'],
        ['F52', 'done', 'Soutien aux signalements publics des autres habitants disponible.', 'site', '/espace/participation'],
        ['F63', 'in_progress', 'État des services modifiable ; blocage des démarches à compléter.', 'admin', '/contenus/services'],
        ['F64', 'done', 'État actuel des services visible sur les cartes et les fiches.', 'site', '/services'],
        ['F72', 'in_progress', 'Guide et raccourcis disponibles ; réouverture du guide à compléter.', 'site', '/espace'],
        ['D14', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F27', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F45', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F46', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['D02', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F53', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F54', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F55', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F56', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F57', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F58', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F59', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F60', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F61', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F62', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F65', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F66', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F67', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F68', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F69', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F70', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F71', 'todo', 'Fonctionnalité à réaliser.', '', ''],
    ];
}
