<?php

declare(strict_types=1);

namespace Pilotage\Application\Service;

/** Validated team snapshot, 2026-10-04 (L15–L26 included, waves 19–20 to do); independent of development data and Markdown. */
final class TrackingSnapshot
{
    public const ROWS = [
        ['D01', 'done', 'Inscription et création de l’espace citoyen disponibles.', 'site', '/inscription'],
        ['D03', 'done', 'Connexion et accès à l’espace personnel disponibles.', 'site', '/connexion'],
        ['D04', 'done', 'Envoi d’un message à la mairie avec confirmation.', 'site', '/espace/demandes/nouvelle?type=contact'],
        ['D05', 'done', 'Catalogue et fiches des services municipaux disponibles.', 'site', '/services'],
        ['D06', 'done', 'Actualités de la ville consultables en ligne.', 'site', '/actualites'],
        ['D07', 'done', 'Accueil avec services prioritaires et dernières actualités.', 'site', '/'],
        ['D08', 'done', 'Gestion des membres et de leurs rôles disponible.', 'admin', '/admin/member'],
        ['D09', 'done', 'Accès aux outils administratifs contrôlé par permissions.', 'admin', '/admin/role'],
        ['D11', 'done', 'Suivi des demandes avec état et chronologie.', 'site', '/espace/demandes'],
        ['D12', 'done', 'Guide de démarrage en trois étapes dans l’espace citoyen.', 'site', '/espace'],
        ['D13', 'done', 'Libellés simplifiés et glossaire disponibles.', 'site', '/aide/glossaire'],
        ['D15', 'done', 'Fil d’Ariane disponible pour se repérer dans les pages.', 'site', '/services'],
        ['D16', 'done', 'Confirmation avec référence après l’envoi d’une demande.', 'site', '/espace/demandes/nouvelle?type=contact'],
        ['D17', 'done', 'Compteur des demandes en attente dans la file des agents.', 'admin', '/demandes'],
        ['D18', 'done', 'Publication d’alertes générales visibles en temps réel.', 'admin', '/contenus/alertes'],
        ['D19', 'done', 'Flux des demandes Webcup et suivi de l’équipe disponibles.', 'admin', '/pilotage'],
        ['D20', 'done', 'Réglages d’accessibilité intégrés aux parcours habituels.', 'site', '/'],
        ['F21', 'done', 'Repères, champs et annonces adaptés aux lecteurs d’écran.', 'site', '/inscription'],
        ['F22', 'done', 'File des demandes avec filtres et traitement par les agents.', 'admin', '/demandes'],
        ['F23', 'done', 'Mode contraste élevé disponible dans le panneau Affichage.', 'site', '/'],
        ['F24', 'done', 'Taille du texte réglable dans le panneau Affichage.', 'site', '/'],
        ['F25', 'done', 'Signalement d’un problème avec description et lieu.', 'site', '/espace/demandes/nouvelle?type=report'],
        ['F26', 'done', 'Historique des demandes disponible dans l’espace personnel.', 'site', '/espace/demandes'],
        ['F28', 'done', 'Services prioritaires mis en avant sur l’accueil.', 'site', '/'],
        ['F29', 'done', 'Publication d’alertes ciblées par quartier disponible.', 'admin', '/contenus/alertes'],
        ['F30', 'done', 'Annonces importantes signalées dans les notifications.', 'site', '/espace'],
        ['F31', 'done', 'Recommandations sanitaires diffusées aux citoyens consentants.', 'admin', '/contenus/alertes'],
        ['F32', 'done', 'Recherche de services par mot-clé et catégorie.', 'site', '/services'],
        ['F33', 'done', 'Suppression de son compte depuis le profil citoyen.', 'site', '/espace/profil'],
        ['F34', 'done', 'Consultation et suspension des comptes citoyens disponibles.', 'admin', '/admin/citizens'],
        ['F35', 'done', 'Astuces contextuelles disponibles pour les premières actions.', 'site', '/services'],
        ['F36', 'done', 'Horaires et informations des transports sur les fiches services.', 'site', '/services'],
        ['F37', 'done', 'Protection des connexions et journal des blocages disponibles.', 'admin', '/admin/security'],
        ['F38', 'done', 'État des services, retour prévu et alternatives affichés.', 'site', '/services'],
        ['F39', 'done', 'Réservation, déplacement et annulation de rendez-vous disponibles.', 'site', '/espace/rendez-vous'],
        ['F40', 'in_progress', 'Rappels de rendez-vous implémentés ; planification à vérifier.', 'site', '/espace/rendez-vous'],
        ['F41', 'done', 'Navigation au clavier et focus visible disponibles.', 'site', '/'],
        ['F42', 'done', 'Champs, aides et erreurs reliés pour les technologies d’assistance.', 'site', '/inscription'],
        ['F43', 'done', 'États distingués par un libellé et une icône.', 'site', '/espace/demandes'],
        ['F44', 'done', 'Mise en page adaptée au zoom et aux petits écrans.', 'site', '/'],
        ['F47', 'done', 'Journal des actions avec recherche et filtres disponible.', 'admin', '/admin/journal'],
        ['F48', 'done', 'Auteur, date et détail des modifications consultables.', 'admin', '/admin/journal'],
        ['F49', 'done', 'Notifications des changements d’état des demandes disponibles.', 'site', '/espace'],
        ['F50', 'done', 'Tableau de bord de l’activité disponible pour les agents.', 'admin', '/pilotage/tableau-de-bord'],
        ['F51', 'done', 'Information sur les données et dépôt d’inquiétudes disponibles.', 'site', '/espace/participation'],
        ['F52', 'done', 'Soutien aux signalements publics des autres habitants disponible.', 'site', '/espace/participation'],
        ['F63', 'done', 'Désactivation d’un service avec motif ; démarches bloquées.', 'admin', '/contenus/services'],
        ['F64', 'done', 'État actuel des services visible sur les cartes et les fiches.', 'site', '/services'],
        ['F72', 'done', 'Parcours « Par où commencer » sans inscription.', 'site', '/bienvenue'],
        ['D14', 'in_progress', 'Interface en français, anglais et arabe ; couverture partielle.', 'site', '/'],
        ['F27', 'in_progress', 'Services traduits ; publications et alertes non traduites.', 'site', '/services'],
        ['F45', 'done', 'Carte des services, liste et itinéraire.', 'site', '/carte'],
        ['F46', 'done', 'Numéros et lieux d’urgence en un clic.', 'site', '/urgences'],
        ['D02', 'done', 'Connexion par lien e-mail à usage unique.', 'site', '/connexion'],
        ['F53', 'done', 'Code de vérification par e-mail activable.', 'site', '/espace/securite'],
        ['F54', 'done', 'Alerte de connexion depuis un nouvel appareil.', 'site', '/espace/securite'],
        ['F55', 'done', 'Export clair des données personnelles.', 'site', '/espace/mes-donnees'],
        ['F56', 'done', 'Récapitulatif imprimable et CSV des demandes.', 'site', '/espace/demandes/recapitulatif'],
        ['F57', 'done', 'Diagnostic EcoIndex et page Sobriété.', 'site', '/sobriete'],
        ['F58', 'done', 'Chargement sobre des principaux parcours.', 'site', '/sobriete'],
        ['F59', 'done', 'Mode hors ligne et brouillons de formulaire.', 'site', '/sobriete'],
        ['F60', 'done', 'Pages sans image lourde (SVG seulement).', 'site', '/sobriete'],
        ['F61', 'done', 'Allègement pour les appareils peu puissants.', 'site', '/sobriete'],
        ['F62', 'done', 'Mode léger dans le panneau Affichage.', 'site', '/'],
        ['F65', 'done', 'Consultations avec accusé et résultats.', 'site', '/participer'],
        ['F66', 'done', 'Avis non officiel sur un projet avec accusé.', 'site', '/projets'],
        ['F67', 'done', 'Projets en cours filtrables avec étapes.', 'site', '/projets'],
        ['F68', 'done', 'Boîte à idées avec suivi des statuts.', 'site', '/participer/idees'],
        ['F69', 'done', 'Durcissement sécurité et chiffrement au repos.', 'site', '/vos-donnees'],
        ['F70', 'done', 'Données sensibles masquées, affichage journalisé.', 'admin', '/demandes'],
        ['F71', 'done', 'Comptes créés à l’accueil, sans e-mail.', 'admin', '/demandes/accueil'],
        ['D10', 'done', 'Recherche tolérante des services.', 'site', '/services'],
        ['F75', 'done', 'Repérage des demandes similaires.', 'admin', '/demandes'],
        ['F77', 'done', 'Mode allégé en cas de surcharge.', 'site', '/'],
        ['F78', 'done', 'Cache public, index et réglages de montée en charge.', '', ''],
        ['F79', 'done', 'Tri et filtres des demandes par sujet.', 'site', '/espace/demandes'],
        ['F80', 'done', 'Priorités et file triée pour les agents.', 'admin', '/demandes'],
        ['F81', 'done', 'Protection anti-robots des formulaires.', 'site', '/inscription'],
        ['F82', 'done', 'Envoi multiple d’un formulaire empêché.', 'site', '/espace/demandes/nouvelle?type=contact'],
        ['F83', 'done', 'Accusé de réception vérifiable.', 'site', '/verifier-accuse'],
        ['F84', 'done', 'Réponses des agents aux demandes.', 'admin', '/demandes'],
        ['F85', 'done', 'Détection d’activité inhabituelle.', 'admin', '/admin/activite-inhabituelle'],
        ['F86', 'done', 'Urgence médicale traitée en priorité.', 'site', '/espace/demandes/nouvelle'],
        ['F87', 'done', 'Sauvegarde et restauration vérifiées.', 'admin', '/admin/sauvegardes'],
        ['F89', 'done', 'Version en clair des services et publications.', 'site', '/services'],
        ['F90', 'done', 'Bouton « Expliquer simplement ».', 'site', '/services'],
        ['F91', 'done', 'Assistant d’orientation des habitants.', 'site', '/aide/assistant'],
        ['F92', 'done', 'Orientation depuis une description libre.', 'site', '/aide/assistant'],
        ['F73', 'done', 'Messages officiels du Haut Conseil en tête du site.', 'site', '/messages-officiels'],
        ['F74', 'done', 'Horaires et adresses des associations partenaires.', 'site', '/partenaires'],
        ['F76', 'done', 'Avis sur un service avec réponse des agents.', 'site', '/espace/avis'],
        ['F88', 'done', 'Exports CSV/JSON des données de suivi.', 'admin', '/pilotage/exports'],
        ['F93', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F94', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F95', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F96', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F97', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F98', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F99', 'todo', 'Fonctionnalité à réaliser.', '', ''],
        ['F100', 'todo', 'Fonctionnalité à réaliser.', '', ''],
    ];
}
