iam:
    resource:
        path: ../src/IAM/Application/Controller/
        namespace: IAM\Application\Controller
    type: attribute

administration:
    resource:
        path: ../src/Administration/Application/Controller/
        namespace: Administration\Application\Controller
    type: attribute

citizen:
    resource:
        path: ../src/Citizen/Application/Controller/
        namespace: Citizen\Application\Controller
    type: attribute

api_login_check:
    path: /api/login_check
